export enum EnvironmentsEnum {
  PORT = 'PORT',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_NAME = 'DB_NAME',
  DB_TYPE = 'DB_TYPE',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  MAIL_PORT = 'MAIL_PORT',
  MAIL_HOST = 'MAIL_HOST',
  MAIL_FROM_NAME = 'MAIL_FROM_NAME',
  MAIL_FROM_ADDRESS = 'MAIL_FROM_ADDRESS',
  MAIL_FROM_PASSWORD = 'MAIL_FROM_PASSWORD',
  JWT_SECRET = 'JWT_SECRET'
}
